### ISSUE TITLE
滑动返回手势失效了

### ISSUE THREAD

**Issue by wcgCoding** [ws00801526/SuspensionEntrance#1]
我再导航控制器里面做了修改之后系统的滑动返回失效如何处理呢？

**Comment by wcgCoding** [comment]
其他界面

**Comment by wcgCoding** [comment]
提供的demo就有这个问题。点击播放按钮 push normal控制器，这个控制器就不能滑动返回了。

**Comment by ws00801526** [comment]
这个就是需要禁止系统返回手势, 然后通过自定义手势来处理右滑返回效果.
整体的系统返回手势控制, 还是可以在每个ViewController中进行处理.

您这边失效的话, 可以考虑搭配[FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture), 通过fd_interactivePopDisabled来控制

**Comment by wcgCoding** [comment]
> 这个就是需要禁止系统返回手势, 然后通过自定义手势来处理右滑返回效果.
> 整体的系统返回手势控制, 还是可以在每个ViewController中进行处理.
> 
> 您这边失效的话, 可以考虑搭配[FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture), 通过fd_interactivePopDisabled来控制

好的 谢谢啦~
